# Generated by Django 4.1 on 2022-08-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
