# Generated by Django 4.1 on 2022-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pricee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
