# Generated by Django 4.1 on 2022-08-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='perfume',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shirt',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trouser',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='watch',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='perfume',
        ),
        migrations.DeleteModel(
            name='shirt',
        ),
        migrations.DeleteModel(
            name='trouser',
        ),
        migrations.DeleteModel(
            name='watch',
        ),
    ]
