# Generated by Django 4.1 on 2022-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_order_date_ordered_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
