# Generated by Django 4.1 on 2023-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_deliveryaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
