# Generated by Django 4.1 on 2023-06-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_product_category_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_desc',
        ),
    ]
